name: whistle-构建和提交docker

on:
  push:
    branches: [main]
    paths: 
      - "whistle/**"
      - "whistle/proxy/**"
      - ".github/workflows/whistle.yml"
      - "!**.md"
  schedule: 
    - cron: '0 2 2 * *' # Weekly on Sundays at 02:00 

jobs:
  
  setup-build-publish:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像
    steps:
    
    - name: Checkout
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v2.3.2



              
    - name: whistle-latest
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/whistle
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./whistle/
        dockerfile: whistle/Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        # build_args: GIT_BRANCH=master
        # Adds labels with git repository information to the built image
        add_git_labels: true  

    - name: whistle-supervisor
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/whistle
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: supervisor
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./whistle/supervisor/
        dockerfile: whistle/supervisor/Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        # build_args: GIT_BRANCH=master
        # Adds labels with git repository information to the built image
        add_git_labels: true  

              
#########################proxy#########################################

    - name: whistle-proxy
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/whistle
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: proxy
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./whistle/proxy
        dockerfile: whistle/proxy/Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        # build_args: GIT_BRANCH=master
        # Adds labels with git repository information to the built image
        add_git_labels: true  

              
    - name: whistle-proxy--ali
      uses: docker/build-push-action@v1.1.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.USERNAME_ALI }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD_ALI }}
        # Docker repository to tag the image with
        repository: adockero/whistle
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: proxy
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./whistle/proxy
        dockerfile: whistle/proxy/Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        # build_args: GIT_BRANCH=master
        # Adds labels with git repository information to the built image
        add_git_labels: true     
   
